plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'

    id 'androidx.navigation.safeargs.kotlin'
}

apply plugin: 'com.android.application'

android {
    namespace 'com.test'
    compileSdk 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    defaultConfig {
        applicationId "com.test.glucn"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

// ДОБАВЬТЕ ЭТОТ БЛОК (если используете Kotlin)
    kotlinOptions {
        jvmTarget = "17"
    }
    flavorDimensions "default"

    // Добавляем пустой блок productFlavors.
    // Без него измерение не будет иметь смысла, но ошибка уйдет.
    productFlavors {
        // Создаем один стандартный вкус (flavor).
        standard {
            dimension "default"
        }
    }
    productFlavors {
        generic {
            dimension "default"
        }
        accuchek_smartguide {
            dimension "default"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.github.NightscoutFoundation:xDrip:master-SNAPSHOT'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation libs.constraint.layout
    implementation 'androidx.core:core:1.9.0'
    implementation 'androidx.lifecycle:lifecycle-livedata:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.7'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.7'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}


configurations.all {
    resolutionStrategy {
        force "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0"
        force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0"
    }
}
