plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'androidx.navigation.safeargs.kotlin'
}

android {
    namespace 'com.test'
    compileSdk 35

    defaultConfig {
        applicationId "com.test.glucn"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    flavorDimensions "default"
    productFlavors {
        standard {
            dimension "default"
        }
        generic {
            dimension "default"
        }
        accuchek_smartguide {
            dimension "default"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    def nav_version = "2.7.7"

    // Navigation (только один раз!)
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    // Другие зависимости
    implementation 'com.github.NightscoutFoundation:xDrip:master-SNAPSHOT'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.fragment:fragment-ktx:1.6.2'
    implementation 'com.github.AppDevNext:AndroidChart:3.1.0.27'
}

// УДАЛИТЕ блок configurations.all - он вызывает конфликты версий